// Hook data extracted from AdHookVault (intel.adhookvault.com)
// 543 hooks with categorization metadata

import hooksJson from './hooks-data.json'

export interface Hook {
  id: string
  trafficType: "COLD" | "WARM"
  awarenessStage: "UNAWARE" | "PROBLEM AWARE" | "SOLUTION AWARE" | "PRODUCT AWARE"
  hookTemplate: string
  emotionalTrigger: string
  psychology: string
  angleCategory: string
  tone: string
}

export const TRAFFIC_TYPES = ["COLD", "WARM"] as const
export const AWARENESS_STAGES = ["UNAWARE", "PROBLEM AWARE", "SOLUTION AWARE", "PRODUCT AWARE"] as const
export const TONES = ["Authority/Trust Statement", "Bold Statement", "Challenge/Call-to-Action", "Contrarian Opinion", "Curiosity Gap", "Desire/Future State", "First-Person Direct Statement", "Humor Hook", "If/Then Statement", "Metaphor/Analogy", "Objection Handling", "Pain Alignment (Obvious Yes Question)", "Question Based Hook", "Sentiment/Pain Prompt", "Shocking Statistic", "Social Proof Mention", "Story-Based Hook"] as const

export const EMOTIONAL_TRIGGERS = ["AUTHORITY/DESIRE", "AUTHORITY/FEAR", "AUTHORITY/HOPE", "AUTHORITY/RELIEF", "AUTHORITY/TRUST", "BELONGING", "BELONGING/CURIOSITY", "BELONGING/HUMOR", "BELONGING/RELIEF", "BELONGING/TRIBE", "BELONGING/TRUST", "CONCERN/AUTHORITY", "CURIOSITY", "CURIOSITY/AUTHORITY", "CURIOSITY/CONCERN", "CURIOSITY/DESIRE", "CURIOSITY/EXCITEMENT", "CURIOSITY/HUMOR", "CURIOSITY/SKEPTICISM", "CURIOSITY/SURPRISE", "CURIOSITY/TRUST", "DESIRE/BELONGING", "DESIRE/EXCITEMENT", "DESIRE/FOMO", "DESIRE/FUTURE STATE", "DESIRE/SHOCK", "DESIRE/TRUST", "DISGUST/RELATABILITY", "DISGUST/RELIEF", "EMPATHY/CURIOSITY", "EMPATHY/RELATABILITY", "EMPATHY/TRUST", "EXCITEMENT", "EXCITEMENT/AUTHORITY", "EXCITEMENT/BELONGING", "EXCITEMENT/HOPE", "EXCITEMENT/INSPIRATION", "FEAR", "FEAR/CURIOSITY", "FEAR/EMPATHY", "FEAR/RELIEF", "FEAR/SHOCK", "FEAR/TRUST", "FEAR/URGENCY", "FOMO", "FOMO/CURIOSITY", "FRUSTRATION/BELONGING", "FRUSTRATION/RELIEF", "GREED (DESIRE FOR GAIN)", "HOPE/CURIOSITY", "HOPE/TRUST", "HUMOR/BELONGING", "HUMOR/CURIOSITY", "HUMOR/DESIRE", "HUMOR/RELATABILITY", "HUMOR/TRUST", "INSPIRATION/TRUST", "NOSTALGIA/CURIOSITY", "RELATABILITY/CURIOSITY", "RELATABILITY/DISCOMFORT", "RELATABILITY/FEAR", "RELATABILITY/HOPE", "RELATABILITY/SHOCK", "RELIEF", "RELIEF/CURIOSITY", "RELIEF/DESIRE", "RELIEF/EXCITEMENT", "SENTIMENT", "SHOCK/AUTHORITY", "SHOCK/CURIOSITY", "SHOCK/DESIRE", "SHOCK/DISGUST", "SHOCK/EMPATHY", "SHOCK/HOPE", "SHOCK/RELATABILITY", "SHOCK/RELIEF", "SHOCK/TRUST", "SURPRISE/AUTHORITY", "SURPRISE/CURIOSITY", "SURPRISE/DESIRE", "SURPRISE/HOPE", "SURPRISE/SHOCK", "SURPRISE/TRUST", "TRUST", "TRUST/AWE", "TRUST/CLARITY", "TRUST/CURIOSITY", "TRUST/EXCITEMENT", "TRUST/FOMO", "TRUST/RELATABILITY", "TRUST/RELIEF", "TRUST/SENTIMENT", "URGENCY/DESIRE", "URGENCY/DESIRE FOR GAIN", "URGENCY/FEAR", "URGENCY/RELIEF"] as const

export const ANGLE_CATEGORIES = ["Belonging / Lifestyle Focus", "Belonging/Problem Focus", "Chalenge/Offer Focus", "Community / Opportunity Focus", "Contrarian / Lifestyle", "Contrarian / Objection Handling", "Contrarian / Pain Prompt", "Contrarian / Problem Focus", "Contrarian / Results Focus", "Contrarian / Social Proof", "Contrarian / Unique Value Prop", "Credentials / How-To", "Credentials Focus", "Credentials/Social Proof", "Curiosity Gap / Education", "Curiosity Gap / Engagement", "Curiosity Gap / Lifestyle", "Curiosity Gap / Mystery", "Curiosity Gap / Offer", "Curiosity Gap / Story", "Curuosity Cap/Opportunity", "DESIRE/FUTURE STATE FOCUS", "Desire / Future State Focus", "Education / Authority", "Education / Credentials", "Education / How-To", "Education / Problem Focus", "Education / Solution Focus", "Education / Trend Focus", "Emotional / Opportunity Focus", "Engagement / Pain Prompt", "Future State / Offer", "Future-State / Story", "Guarantee Focus", "Humor / Offer", "Lifestyle / Humor (Offer)", "Lifestyle / Pain Prompt", "Nostalgia / Lifestyle", "Objection Handling", "Objection Handling / Offer", "Offer / Future-State", "Offer / Guarantee Focus", "Offer / How-To", "Offer / Lifestyle", "Offer / Trend Focus", "Offer / Value Focus", "Offer Focus", "Offer/ Oportunity Focus", "Offer/Education Focus", "PRODUCT/SOLUTION FOCUS", "Pain Alignment (Obvious Yes)", "Pain Prompt / Opportunity", "Pain Prompt / Problem Focus", "Pain Prompt / Product Contrast", "Pain Prompt / Story", "Problem - > Solution", "Problem / Authority Focus", "Problem / Health Focus", "Problem / Risk Focus", "Problem/Opportunity Focus", "Product Demo / Challenge", "Product Demo / Comparison", "Product Demo / How-To", "Product Demo / Trend Focus", "Product Demo/Entertainment", "Product Demo/Results", "Product/Solution Focus", "Question / Opportunity", "Scarcity Focus", "Scarcity/Objection Handling", "Sentiment/Pain Prompt", "Shocking Statistic / Education", "Shocking Statistic / Opportunity", "Shocking Statistic / Problem", "Social Proof / Lifestyle", "Social Proof / Research Focus", "Social Proof/ Pain Focus", "Social Proof/Authority", "Social Proof/Results Focus", "Social Proof/Story Focus", "Social Proof/Trend Focus", "Social Proof/Value", "Story / Empathy", "Story / Lifestyle", "Story / Opportunity Focus", "Story / Problem Focus", "Story / Results", "Story / Solution Focus", "Unique Value Prop Focus"] as const

export const hooks: Hook[] = hooksJson as Hook[]
